site_name: pystapi
site_url: https://stapi-spec.github.io/pystapi
repo_url: https://github.com/stapi-spec/pystapi/
repo_name: pystapi
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: img/stapi.png
  favicon: img/stapi.png
  features:
    - navigation.indexes

nav:
  - index.md
  - stapi-pydantic.md
  - stapi-fastapi.md
  - pystapi-client.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
